### ISSUE TITLE
Build task

### ISSUE THREAD

**Issue by dimaursu** [StarpTech/gulp-prestashop#1]
A build task would help a lot, for generating the zip file. Sometimes PrestaShop spits errors on me, because of the newer PHP version I use. Also, another useful task would be "autoindex", to add that file with the copyright notice. there is a [php project](https://github.com/jmcollin/autoindex) that does that, but it's too much, imo.

**Comment by StarpTech** [comment]
Hi, unfortunately, I didn't recognize that issue. If you have any further questions feel free to open a new issue.
